// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_news_app/test/repository/news_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_news_app/app/data/data_source/local/news_cache_service.dart'
    as _i9;
import 'package:flutter_news_app/app/data/data_source/remote/news_service.dart'
    as _i3;
import 'package:flutter_news_app/app/data/model/category_with_news_model.dart'
    as _i7;
import 'package:flutter_news_app/app/data/model/news_model.dart' as _i6;
import 'package:flutter_news_app/core/connection/network_info.dart' as _i8;
import 'package:flutter_news_app/core/error/failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NewsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsService extends _i1.Mock implements _i3.NewsService {
  MockNewsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.NewsModel>>> fetchNews({
    bool? isLatest,
    bool? forYou,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNews,
          [],
          {
            #isLatest: isLatest,
            #forYou: forYou,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.NewsModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.NewsModel>>(
          this,
          Invocation.method(
            #fetchNews,
            [],
            {
              #isLatest: isLatest,
              #forYou: forYou,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.NewsModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.NewsModel>>> fetchNewsByCategory({
    required String? categoryId,
    int? page,
    int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNewsByCategory,
          [],
          {
            #categoryId: categoryId,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.NewsModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.NewsModel>>(
          this,
          Invocation.method(
            #fetchNewsByCategory,
            [],
            {
              #categoryId: categoryId,
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.NewsModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.CategoryWithNewsModel>>>
      fetchCategoriesWithNews({
    int? page,
    int? pageSize,
    bool? isLatest,
    bool? forYou,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #fetchCategoriesWithNews,
              [],
              {
                #page: page,
                #pageSize: pageSize,
                #isLatest: isLatest,
                #forYou: forYou,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i7.CategoryWithNewsModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.CategoryWithNewsModel>>(
              this,
              Invocation.method(
                #fetchCategoriesWithNews,
                [],
                {
                  #page: page,
                  #pageSize: pageSize,
                  #isLatest: isLatest,
                  #forYou: forYou,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i7.CategoryWithNewsModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> saveNews(
          {required String? newsId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNews,
          [],
          {#newsId: newsId},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #saveNews,
            [],
            {#newsId: newsId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSavedNews(
          {required String? savedNewsId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSavedNews,
          [],
          {#savedNewsId: savedNewsId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteSavedNews,
            [],
            {#savedNewsId: savedNewsId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [INetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkInfo extends _i1.Mock implements _i8.INetworkInfo {
  MockINetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get currentConnectivityResult => (super.noSuchMethod(
        Invocation.getter(#currentConnectivityResult),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [NewsCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsCacheService extends _i1.Mock implements _i9.NewsCacheService {
  MockNewsCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePopularNews(List<_i6.NewsModel>? news) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePopularNews,
          [news],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.NewsModel>?> getPopularNews() => (super.noSuchMethod(
        Invocation.method(
          #getPopularNews,
          [],
        ),
        returnValue: _i4.Future<List<_i6.NewsModel>?>.value(),
      ) as _i4.Future<List<_i6.NewsModel>?>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isCacheValid() => (super.noSuchMethod(
        Invocation.method(
          #isCacheValid,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int?> getCacheAgeInMinutes() => (super.noSuchMethod(
        Invocation.method(
          #getCacheAgeInMinutes,
          [],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
