// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_news_app/test/repository/twitter_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_news_app/app/data/data_source/remote/twitter_service.dart'
    as _i3;
import 'package:flutter_news_app/app/data/model/tweet_model.dart' as _i6;
import 'package:flutter_news_app/core/connection/network_info.dart' as _i7;
import 'package:flutter_news_app/core/error/failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TwitterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTwitterService extends _i1.Mock implements _i3.TwitterService {
  MockTwitterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TweetModel>>> fetchTweets({
    int? page,
    int? pageSize,
    bool? isPopular,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTweets,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #isPopular: isPopular,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.TweetModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.TweetModel>>(
          this,
          Invocation.method(
            #fetchTweets,
            [],
            {
              #page: page,
              #pageSize: pageSize,
              #isPopular: isPopular,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TweetModel>>>);
}

/// A class which mocks [INetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkInfo extends _i1.Mock implements _i7.INetworkInfo {
  MockINetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get currentConnectivityResult => (super.noSuchMethod(
        Invocation.getter(#currentConnectivityResult),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
